# Generated by Django 5.0.6 on 2024-06-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydata',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name='propertydata',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True),
        ),
    ]
