# Generated by Django 5.0.6 on 2024-06-11 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.IntegerField()),
                ('down_payment', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('loan_term', models.IntegerField()),
                ('rental_income', models.FloatField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_data.propertydata')),
            ],
        ),
    ]
