# Generated by Django 5.0.6 on 2024-06-11 23:25

import market_data.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('zipcode', models.CharField(primary_key=True, serialize=False, validators=[market_data.validators.validate_zip_code])),
                ('population', models.BigIntegerField()),
                ('unemployment', models.FloatField()),
            ],
        ),
    ]
