# Generated by Django 5.0.6 on 2024-06-13 20:19

import market_data.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(validators=[market_data.validators.validate_zip_code])),
                ('year', models.IntegerField()),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('median_household_income', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('unemployment', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
        ),
    ]
